### ISSUE TITLE
Рисование траектории. Анимация закона движения.

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/WPF2021#10]
[code](https://github.com/jarosloov/WPF2021/tree/main/FirstCourseWork)
![image](https://user-images.githubusercontent.com/60881838/119681954-ee0c0a80-be5b-11eb-835f-74229d7eab66.png)

**Comment by justjune** [comment]
У меня мультики закомментированы....

**Comment by jarosloov** [comment]
Если делать с мультиками, то получается очень странно..
формулы все те же, ну время конечно по таймеру, если изменить направление графика по оси Х, то график улетает(
![image](https://user-images.githubusercontent.com/60881838/119867358-4106c000-bf37-11eb-93dd-540a002e4105.png)
