### ISSUE TITLE
Главы 11 и 12 были исключены.

### ISSUE THREAD

**Issue by justjune** [jarosloov/WPF2021#5]
Куда теперь баллы за них ставить?

**Comment by jarosloov** [comment]
Ойй, мы не увидели, когда распределяли, что их нет в Успеваемости. Наверное уже поздно сообщаться другим бригадирам, что их нет по плану.

**Comment by justjune** [comment]
Ну, считаем перевыполнением (только до экзамена мне надо напомнить, чтобы я за них баллы добавил)!

**Comment by jarosloov** [comment]
Ещё, Вы просили написать вам распределение дополнительных глав которые, мы взяли дополнительно, из за нехватки задач.

- Предыдущая неделя  [Глава 7-11] 
- Текущая неделя  [Глава 12-13]
