### ISSUE TITLE
Полёт тела с сопротивлением воздуха

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/WPF2021#6]
[Полёт тела с сопротивлением воздуха](https://github.com/jarosloov/WPF2021/tree/main/BallisticFlight)

**Comment by justjune** [comment]
Воздействие ветра --- пока константа?

**Comment by jarosloov** [comment]
пока да

**Comment by jarosloov** [comment]
[Запись в эксель(анимация изменения данных) + сопротивление зависит от скорости](https://github.com/jarosloov/WPF2021/tree/main/BallisticFlight)

**Comment by justjune** [comment]
Слегка подправил работу с файлом.
