### ISSUE TITLE
Макет с обработчиками. Ввод данных.

### ISSUE THREAD

**Issue by jarosloov** [jarosloov/WPF2021#9]
[Code](https://github.com/jarosloov/WPF2021/tree/main/%5B9%5D%20Data%20input%20and%20output)

**Comment by justjune** [comment]
См. Успеваемость.

**Comment by jarosloov** [comment]
Получается, это не то задание? 
![image](https://user-images.githubusercontent.com/60881838/119181052-8dab5080-ba8a-11eb-8064-4dab21d32935.png)

**Comment by justjune** [comment]
Не получается. Просто я забыл проставить еще и туда. См. Успеваемость. (Спасибо, что проверили.)
